// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tx struct {
	Hash    string      `json:"hash"`
	Raw     string      `json:"raw"`
	Inputs  []*TxInput  `json:"inputs"`
	Outputs []*TxOutput `json:"outputs"`
}

type TxInput struct {
	Tx        *Tx       `json:"tx"`
	Hash      string    `json:"hash"`
	Index     int       `json:"index"`
	PrevHash  string    `json:"prev_hash"`
	PrevIndex int       `json:"prev_index"`
	Output    *TxOutput `json:"output"`
}

type TxOutput struct {
	Tx     *Tx        `json:"tx"`
	Hash   string     `json:"hash"`
	Index  int        `json:"index"`
	Amount int        `json:"amount"`
	Script string     `json:"script"`
	Spends []*TxInput `json:"spends"`
}
