// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SetName struct {
	Tx     *Tx    `json:"tx"`
	TxHash string `json:"tx_hash"`
	Lock   *Lock  `json:"lock"`
	Name   string `json:"name"`
}

type SetPic struct {
	Tx     *Tx    `json:"tx"`
	TxHash string `json:"tx_hash"`
	Lock   *Lock  `json:"lock"`
	Pic    string `json:"pic"`
}

type SetProfile struct {
	Tx     *Tx    `json:"tx"`
	TxHash string `json:"tx_hash"`
	Lock   *Lock  `json:"lock"`
	Text   string `json:"text"`
}
