// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: queue.proto

package queue_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	Order_ASC  Order = 0
	Order_DESC Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Order_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_queue_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_queue_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

type Messages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

func (x *Messages) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           []byte                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetUid() []byte {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ErrorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReply) Reset() {
	*x = ErrorReply{}
	mi := &file_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReply) ProtoMessage() {}

func (x *ErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReply.ProtoReflect.Descriptor instead.
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MessageUids struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Uids          [][]byte               `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUids) Reset() {
	*x = MessageUids{}
	mi := &file_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUids) ProtoMessage() {}

func (x *MessageUids) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUids.ProtoReflect.Descriptor instead.
func (*MessageUids) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{3}
}

func (x *MessageUids) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MessageUids) GetUids() [][]byte {
	if x != nil {
		return x.Uids
	}
	return nil
}

type RequestSingle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Uid           []byte                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSingle) Reset() {
	*x = RequestSingle{}
	mi := &file_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSingle) ProtoMessage() {}

func (x *RequestSingle) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSingle.ProtoReflect.Descriptor instead.
func (*RequestSingle) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{4}
}

func (x *RequestSingle) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RequestSingle) GetUid() []byte {
	if x != nil {
		return x.Uid
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Uids          [][]byte               `protobuf:"bytes,5,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request) GetUids() [][]byte {
	if x != nil {
		return x.Uids
	}
	return nil
}

type RequestStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Prefixes      [][]byte               `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStream) Reset() {
	*x = RequestStream{}
	mi := &file_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStream) ProtoMessage() {}

func (x *RequestStream) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStream.ProtoReflect.Descriptor instead.
func (*RequestStream) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{6}
}

func (x *RequestStream) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RequestStream) GetPrefixes() [][]byte {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{7}
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{8}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopicListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListReply) Reset() {
	*x = TopicListReply{}
	mi := &file_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListReply) ProtoMessage() {}

func (x *TopicListReply) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListReply.ProtoReflect.Descriptor instead.
func (*TopicListReply) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{9}
}

func (x *TopicListReply) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{10}
}

func (x *CountRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CountRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type TopicCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicCount) Reset() {
	*x = TopicCount{}
	mi := &file_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicCount) ProtoMessage() {}

func (x *TopicCount) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicCount.ProtoReflect.Descriptor instead.
func (*TopicCount) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{11}
}

func (x *TopicCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RequestPrefixes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Prefixes      []*RequestPrefix       `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Order         Order                  `protobuf:"varint,4,opt,name=order,proto3,enum=queue_pb.Order" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPrefixes) Reset() {
	*x = RequestPrefixes{}
	mi := &file_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPrefixes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPrefixes) ProtoMessage() {}

func (x *RequestPrefixes) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPrefixes.ProtoReflect.Descriptor instead.
func (*RequestPrefixes) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{12}
}

func (x *RequestPrefixes) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RequestPrefixes) GetPrefixes() []*RequestPrefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *RequestPrefixes) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RequestPrefixes) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ASC
}

type RequestPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Start         []byte                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPrefix) Reset() {
	*x = RequestPrefix{}
	mi := &file_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPrefix) ProtoMessage() {}

func (x *RequestPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPrefix.ProtoReflect.Descriptor instead.
func (*RequestPrefix) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{13}
}

func (x *RequestPrefix) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *RequestPrefix) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RequestPrefix) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_queue_proto protoreflect.FileDescriptor

const file_queue_proto_rawDesc = "" +
	"\n" +
	"\vqueue.proto\x12\bqueue_pb\"9\n" +
	"\bMessages\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.queue_pb.MessageR\bmessages\"i\n" +
	"\aMessage\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\fR\x03uid\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\"\n" +
	"\n" +
	"ErrorReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"7\n" +
	"\vMessageUids\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\fR\x04uids\"7\n" +
	"\rRequestSingle\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\fR\x03uid\"3\n" +
	"\aRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04uids\x18\x05 \x03(\fR\x04uids\"A\n" +
	"\rRequestStream\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bprefixes\x18\x02 \x03(\fR\bprefixes\"\x0e\n" +
	"\fEmptyRequest\"1\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"9\n" +
	"\x0eTopicListReply\x12'\n" +
	"\x06topics\x18\x01 \x03(\v2\x0f.queue_pb.TopicR\x06topics\"<\n" +
	"\fCountRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\fR\x06prefix\"\"\n" +
	"\n" +
	"TopicCount\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\x99\x01\n" +
	"\x0fRequestPrefixes\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x123\n" +
	"\bprefixes\x18\x02 \x03(\v2\x17.queue_pb.RequestPrefixR\bprefixes\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12%\n" +
	"\x05order\x18\x04 \x01(\x0e2\x0f.queue_pb.OrderR\x05order\"S\n" +
	"\rRequestPrefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x14\n" +
	"\x05start\x18\x02 \x01(\fR\x05start\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit*\x1a\n" +
	"\x05Order\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\xc4\x04\n" +
	"\x05Queue\x12:\n" +
	"\fSaveMessages\x12\x12.queue_pb.Messages\x1a\x14.queue_pb.ErrorReply\"\x00\x12?\n" +
	"\x0eDeleteMessages\x12\x15.queue_pb.MessageUids\x1a\x14.queue_pb.ErrorReply\"\x00\x12:\n" +
	"\n" +
	"GetMessage\x12\x17.queue_pb.RequestSingle\x1a\x11.queue_pb.Message\"\x00\x126\n" +
	"\vGetMessages\x12\x11.queue_pb.Request\x1a\x12.queue_pb.Messages\"\x00\x12@\n" +
	"\rGetByPrefixes\x12\x19.queue_pb.RequestPrefixes\x1a\x12.queue_pb.Messages\"\x00\x12C\n" +
	"\x11GetStreamMessages\x12\x17.queue_pb.RequestStream\x1a\x11.queue_pb.Message\"\x000\x01\x12B\n" +
	"\fGetTopicList\x12\x16.queue_pb.EmptyRequest\x1a\x18.queue_pb.TopicListReply\"\x00\x12A\n" +
	"\x0fGetMessageCount\x12\x16.queue_pb.CountRequest\x1a\x14.queue_pb.TopicCount\"\x00\x12<\n" +
	"\n" +
	"CompactAll\x12\x16.queue_pb.EmptyRequest\x1a\x14.queue_pb.ErrorReply\"\x00B-Z+github.com/memocash/index/db/proto/queue_pbb\x06proto3"

var (
	file_queue_proto_rawDescOnce sync.Once
	file_queue_proto_rawDescData []byte
)

func file_queue_proto_rawDescGZIP() []byte {
	file_queue_proto_rawDescOnce.Do(func() {
		file_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)))
	})
	return file_queue_proto_rawDescData
}

var file_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_queue_proto_goTypes = []any{
	(Order)(0),              // 0: queue_pb.Order
	(*Messages)(nil),        // 1: queue_pb.Messages
	(*Message)(nil),         // 2: queue_pb.Message
	(*ErrorReply)(nil),      // 3: queue_pb.ErrorReply
	(*MessageUids)(nil),     // 4: queue_pb.MessageUids
	(*RequestSingle)(nil),   // 5: queue_pb.RequestSingle
	(*Request)(nil),         // 6: queue_pb.Request
	(*RequestStream)(nil),   // 7: queue_pb.RequestStream
	(*EmptyRequest)(nil),    // 8: queue_pb.EmptyRequest
	(*Topic)(nil),           // 9: queue_pb.Topic
	(*TopicListReply)(nil),  // 10: queue_pb.TopicListReply
	(*CountRequest)(nil),    // 11: queue_pb.CountRequest
	(*TopicCount)(nil),      // 12: queue_pb.TopicCount
	(*RequestPrefixes)(nil), // 13: queue_pb.RequestPrefixes
	(*RequestPrefix)(nil),   // 14: queue_pb.RequestPrefix
}
var file_queue_proto_depIdxs = []int32{
	2,  // 0: queue_pb.Messages.messages:type_name -> queue_pb.Message
	9,  // 1: queue_pb.TopicListReply.topics:type_name -> queue_pb.Topic
	14, // 2: queue_pb.RequestPrefixes.prefixes:type_name -> queue_pb.RequestPrefix
	0,  // 3: queue_pb.RequestPrefixes.order:type_name -> queue_pb.Order
	1,  // 4: queue_pb.Queue.SaveMessages:input_type -> queue_pb.Messages
	4,  // 5: queue_pb.Queue.DeleteMessages:input_type -> queue_pb.MessageUids
	5,  // 6: queue_pb.Queue.GetMessage:input_type -> queue_pb.RequestSingle
	6,  // 7: queue_pb.Queue.GetMessages:input_type -> queue_pb.Request
	13, // 8: queue_pb.Queue.GetByPrefixes:input_type -> queue_pb.RequestPrefixes
	7,  // 9: queue_pb.Queue.GetStreamMessages:input_type -> queue_pb.RequestStream
	8,  // 10: queue_pb.Queue.GetTopicList:input_type -> queue_pb.EmptyRequest
	11, // 11: queue_pb.Queue.GetMessageCount:input_type -> queue_pb.CountRequest
	8,  // 12: queue_pb.Queue.CompactAll:input_type -> queue_pb.EmptyRequest
	3,  // 13: queue_pb.Queue.SaveMessages:output_type -> queue_pb.ErrorReply
	3,  // 14: queue_pb.Queue.DeleteMessages:output_type -> queue_pb.ErrorReply
	2,  // 15: queue_pb.Queue.GetMessage:output_type -> queue_pb.Message
	1,  // 16: queue_pb.Queue.GetMessages:output_type -> queue_pb.Messages
	1,  // 17: queue_pb.Queue.GetByPrefixes:output_type -> queue_pb.Messages
	2,  // 18: queue_pb.Queue.GetStreamMessages:output_type -> queue_pb.Message
	10, // 19: queue_pb.Queue.GetTopicList:output_type -> queue_pb.TopicListReply
	12, // 20: queue_pb.Queue.GetMessageCount:output_type -> queue_pb.TopicCount
	3,  // 21: queue_pb.Queue.CompactAll:output_type -> queue_pb.ErrorReply
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_queue_proto_init() }
func file_queue_proto_init() {
	if File_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_proto_goTypes,
		DependencyIndexes: file_queue_proto_depIdxs,
		EnumInfos:         file_queue_proto_enumTypes,
		MessageInfos:      file_queue_proto_msgTypes,
	}.Build()
	File_queue_proto = out.File
	file_queue_proto_goTypes = nil
	file_queue_proto_depIdxs = nil
}
